version: '3.8'

services:
  rikai:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - RIKAI_DBHOST=database
    container_name: rikai
  database:
    image: vaticle/typedb:latest
    ports:
      - 1729:1729