on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-checks:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Install Code Formatters
        run: |
          pip install pytest black mypy isort pydocstyle pycodestyle
      - name: black
        run: black --check .
      - name: mypy
        run: mypy --install-types --non-interactive -p rikai
      - name: pydocstyle
        run: pydocstyle rikai
      - name: pycodestyle
        run: pycodestyle --config=pyproject.toml rikai
      - name: isort
        run: isort -c .
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Install Pip Requirements
        run: |
          pip install -r requirements.txt
          pip install pytest coverage
      - name: Run Tests
        run: |
          coverage run --source . -m pytest
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: Coverage Report
          path: coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          verbose: true