on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-checks:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Install Code Formatters
        run: |
          pip install black mypy isort pydocstyle pycodestyle
          pip install types-PyYAML types-pytest
      - name: Run Checks
        run: |
          black --check .
          mypy --install-types --non-interactive -p rikai
          pydocstyle rikai
          pycodestyle --max-line-length=140 rikai
          isort -c .
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Install Pip Requirements
        run: |
          pip install -r requirements.txt
          pip install pytest coverage
      - name: Run Tests
        run: |
          coverage run --source . -m pytest
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: Coverage Report
          path: coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          verbose: true