on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  check:
    name: Run code quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: weibullguy/python-lint-plus@v1.11.0
        with:
          python-version: "3.10"
          use-black: true
          use-isort: true
          use-mypy: true
          extra-black-options: "--line-length 140"
          
